### ISSUE TITLE
未限制发言频率，但无法推送抢地主相关

### ISSUE THREAD

**Issue by AnyMoonS** [kono-dada/doudizhu#5]
上桌什么的都正常
但一到抢地主就报错
2021-10-03 14:59:52 E/dada.douDiZhu: Exception in coroutine Plugin dada.douDiZhu of dada.douDiZhu
java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=55, errorCode=0, errorMessage=)
        at net.mamoe.mirai.internal.contact.SendMessageHandler.sendMessagePacket(SendMessageHandler.kt:164)
        at net.mamoe.mirai.internal.contact.SendMessageHandler$sendMessagePacket$1.invokeSuspend(SendMessageHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by kono-dada** [comment]
我也不知道是啥问题。这里说的貌似是“send message fail”，为什么呢？不知道哪行代码出了问题，好难找错
